### ISSUE TITLE
Reproducing the results

### ISSUE THREAD

**Issue by serdaryildiz** [oufuzhao/QSD#1]
First, thank you for sharing the CHUK03 dataset checkpoint.

I am currently working on reproducing the results of your work and was wondering if you have plans to release the checkpoints for the Market, MSMT, and Duke datasets.

Access to these checkpoints would greatly help me replicate your results.

Thank you.

**Comment by oufuzhao** [comment]
Thank you for your interest in our work. For your requirement in this regard, I will retrieve additional training checkpoints from the old server and share them further.

**Comment by serdaryildiz** [comment]
Thank you so much for your quick response. I really appreciate your help.

**Comment by oufuzhao** [comment]
Hi, thanks for your waiting. I have released the other checkpoints trained on different datasets, please refer to the "Models" section. If our repository is helpful to your work, I would appreciate it if you could cite our work further. Thank you very much : )

**Comment by serdaryildiz** [comment]
Hi,

Thank you for releasing the additional checkpoints. Your repository has been helpful for my work, and I will definitely cite your work in my research.

Thanks again!
